#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.4.{build}
os: WMF 5
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  NuGetApiKey:
    secure: +lqWVtVRayO6KNlJeu9lrnzmtGXreNPIr1Fn3dhXxYTJAHHAOPCPVWvFVkRX7wlr #This is secured
  MyNonSecureVar: NonSecure
  ModuleName: xkcd
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\AppveyorDeploy.ps1
