# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  PSGalleryKey:
    secure: +lqWVtVRayO6KNlJeu9lrnzmtGXreNPIr1Fn3dhXxYTJAHHAOPCPVWvFVkRX7wlr

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/

install:
  - cinst pester
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
# Test with native PS version
  - ps: . .\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\appveyor.pester.ps1 -Finalize

on_success:
#Deploy to PS Gallery here, using PSGalleryKey env var
  - ps: |
    $Module = 'XKCD'
    $Publish = $true
    $Version = $Env:APPVEYOR_BUILD_VERSION

    $ModuleData = (Get-Module $Module)
    
    If ($Version -and $Version -ne '0.0.1') {
        Try {
            Update-ModuleManifest -Path ($ModuleData.Path) -ModuleVersion $Version
            Write-Verbose "Module manifest updated with -ModuleVersion $Version"

            If ($Publish) {   
                Try {
                    Publish-Module -Name $Module -NuGetApiKey $Env:PSGalleryKey 
                    Write-Verbose "Published $Module to PSGallery"
                } Catch { 
                    Write-Error "Could not publish to PSGallery." -Category ConnectionError
                }
            }

        } Catch { 
            Write-Error "Could not update module manifest." -Category ConnectionError
        }

    }Else{
        Write-Error "No version specified." -Category InvalidArgument
    }
